### ISSUE TITLE
Can we stop notification on top notification bar in devices

### ISSUE THREAD

**Issue by hrpatidar** [transistorsoft/cordova-background-geolocation-SampleApp#10]
Hi Chris,

I have implemented same code as you provided in you sample app. It is working fine. You have developed great plugin. But according to my requirement I don't required any notification in devices on top notification bar while location is changing. So Just plugin will update in JS file and JS function would be target to service api. 

Please let me know if you need more information. 

Thanks.

**Comment by christocracy** [comment]
Of course you don't, that would be insane.

debug: false

On Wednesday, September 23, 2015, hrpatidar <notifications@github.com>
wrote:

> Hi Chris,
>
> I have implemented same code as you provided in you sample app. It is
> working fine. You have developed great plugin. But according to my
> requirement I don't required any notification in devices on top
> notification bar while location is changing. So Just plugin will update in
> JS file and JS function would be target to service api.
>
> Please let me know if you need more information.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/10>
> .
>


-- 
Snet form Gmail Mobile

**Comment by hrpatidar** [comment]
Thanks. it's fine for me now.
