### ISSUE TITLE
Background geolocation is undefined

### ISSUE THREAD

**Issue by ViCoastLLC** [transistorsoft/cordova-background-geolocation-SampleApp#100]
Hi, 

I have added new plugin background geolocation version 2.10.1 
Cordova CLI version :6.5.1

Getting window.backgroundGeolocation is undefined

**Comment by christocracy** [comment]
This is the sample app repo, not the plugin repo.

The plugin does not exist at `window.backgroundGeolocation`, it’s at `window.BackgroundGeolocation`.
