### ISSUE TITLE
URL and locationTemplate get ignored while using the ready() function

### ISSUE THREAD

**Issue by ismailgurler1** [transistorsoft/cordova-background-geolocation-SampleApp#102]
In hello-world.ts the second step is to configure the BackgroundGeolocation instance with the ready() function. However, I am getting a 'status 200 success' whatever URL I use. Changing it to configure() works, but the first few tries the locationTemplate was getting ignored.

**Comment by christocracy** [comment]
The config provided to [`#ready`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#readydefaultconfig-successfn-failurefn) method is applied only at *first launch* of the app after initial install.  Thereafter, `#ready` loads persisted config.

You may provide `reset: true` to always apply supplied config

**Comment by ismailgurler1** [comment]
Thanks for your reply. Reset was already set to true. That's why it's strange it didn't reload the supplied config. 

I did 'cordova prepare android'  and ran the app again to see if there was a change, but unfortunately that had no effect.

**Comment by ismailgurler1** [comment]
I have been trying to get it work for two weeks. 

No matter what I try, I can't get the template to work.

Oddly, if I comment out everything except lat and long, I am getting a scucessful call however.

`this.bgGeo.ready({ reset: true,
      debug: true,
      logLevel: this.bgGeo.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopTimeout: 1,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      url: postUrl,
      httpRootProperty: 'fields',
      locationTemplate:
      // '{"latitude":{"doubleValue":<%= latitude %> },"longitude":{"doubleValue":<%= longitude %>}}',
      // '{ "latitude":{"doubleValue":<%= latitude %> },'
      + '"longitude": { "doubleValue":<%= longitude %> },'
      + '"timestamp": { "timestampValue":<%= timestamp %> },'
      + '"bearing": { "doubleValue":<%= heading %> },'
      + '"uuid": { "stringValue":<%= uuid %> }'
      + '"speed": { "doubleValue":<%= speed %> },'
      + '"accuracy": { "doubleValue":<%= accuracy %> },'
      + '"createdBy": { "stringValue":"tp39yhO45id6HyLNmXvKmEWEGwG3" },'
      + '"manufacturerModel": { "stringValue": "'+ this.device.manufacturer + ' ' + this.device.model  +'" }'
      +'}'
      '{"latitude":{"doubleValue":<%= latitude %> },"longitude":{"doubleValue":<%= longitude %>}, "timestamp":{"stringValue":<%= timestamp %>}',
      toSync: true,
      params: {}
    }, (state) => {
      console.log('- Configure success: ', state);
      // Update UI state (toggle switch, changePace button)
      this.zone.run(() => {
        this.isMoving = state.isMoving;
        this.enabled = state.enabled;
      });
    });`

**Comment by christocracy** [comment]
You're responsible for providing your own double-quotes for string-values.

eg:  **NO**
```
'"timestamp": { "stringValue":<%= timestamp %> },'
```
**YES**:
```
'"timestamp": { "stringValue":"<%= timestamp %>"},'
```

**Comment by ismailgurler1** [comment]
Silly me. I forgot to add those quotes.

I still have the same problem ignoring the provided config(url, template etc.) in the `#ready` method.

I think the `doGetUsername` method in the home.ts file was conflicting with the `ready` method, so I did comment out `doGetUsername` so it won't set the config.  

Changing the url and adding a locationTemplate to the config supplied in the `ready` method will not change anything.

I deleted and installed the app again to see if there was any difference. Much to my surprise, I saw that the app doesn't do any http requests after calling `ready`.

**Comment by christocracy** [comment]
The plugin is very verbose and is talking to you in the logs.  You need to learn to listen to the plugin.  See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) wiki.  The answer is in the logs.

You should always be watching the logs.  Thing of the plugin like a web-server.  With your device plugged into USB:

```
$ adb logcat -s TSLocationManager
```

**Comment by ismailgurler1** [comment]
I'll do some more debugging. I think I can close this one. Thanks anyway.
