### ISSUE TITLE
Issue when used in browser

### ISSUE THREAD

**Issue by srikanth15794** [transistorsoft/cordova-background-geolocation-SampleApp#104]
Everything is working fine in the mobile but when we run in it browser so many issues are coming, for example first i got unhandled error event in event,js, type errors and so many and build is going back and everytime i made a change i have to start with ionic serve. can you please tell me why there is a problem with running in the browser ?

**Comment by christocracy** [comment]
You can’t use this plugin browser.

Only device or simulator.
