### ISSUE TITLE
is this plugin run in backgruond if app is terminated or closed?

### ISSUE THREAD

**Issue by Priyanka4010** [transistorsoft/cordova-background-geolocation-SampleApp#110]
when I used this plugin, location gets on foreground and background but the location is not getting when app is completely closed. any help of urgent base?

**Comment by christocracy** [comment]
This is the SampleApp repo.

Post issues at the plugin repo.

https://github.com/transistorsoft/cordova-background-geolocation-lt

If it’s ios you’re talking about, you need to move at least 200 meters before iOS reboots your app in background and plugin resumes tracking.

If Android, your JavaScript app (and all your listeners are terminated.  Only the plugin’s background service remains running and tracking location.

Post an issue at repo.
