### ISSUE TITLE
Unable to trigger geocode update every 8046m

### ISSUE THREAD

**Issue by KieranBinning** [transistorsoft/cordova-background-geolocation-SampleApp#111]
Currently having some troubles getting it setup to record once every 8046 metres.

I've attached the config keys I've tried along with the corresponding results. Not sure how to progress from here, any advice would be greatly appreciated.
[GeolocationsTestRunResults.xlsx](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/files/2952739/GeolocationsTestRunResults.xlsx)

**Comment by christocracy** [comment]
This is the sample app, not the plugin repo.
