### ISSUE TITLE
Where are modal templates?

### ISSUE THREAD

**Issue by madvas** [transistorsoft/cordova-background-geolocation-SampleApp#12]
Where are files for modal templates for geofences? `add.html` and `show.html` 
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/controllers.js#L39

**Comment by madvas** [comment]
sorry, it's in inlined `index.html`

**Comment by christocracy** [comment]
I’m an Ionic noob.

On Fri, Sep 25, 2015 at 8:43 AM, Matus Lestan <notifications@github.com>
wrote:

> sorry, it's in inlined index.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/12#issuecomment-143209130>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
