### ISSUE TITLE
 wrong distance is calculated

### ISSUE THREAD

**Issue by Jitendranagar** [transistorsoft/cordova-background-geolocation-SampleApp#121]
The  odometer  value  is  1058919  and time  is  "2019-12-09T06:50:45" for id 1611552  and next  odometer  value is  1061805 and  time 2019-12-09T06:50:55 for id 1611553. The time difference  is  5 second and difference in odometer  value is (1061805-1058919)=2886  which is very  big and therefor wrong distance is calculated.  how to fix this issue? 

This issue found multiple times. 
 PFA.
![Tracking_issue](https://user-images.githubusercontent.com/6169697/71002878-2c00ed00-2106-11ea-9895-3e58bb902638.png)

**Comment by christocracy** [comment]
Why are you posting this issue at the SampleApp?

The odometer is correct for the input data.  "Garbage in = Garbage out".  Decrease `desiredOdometerAccuracy` as desired to prevent odometer calculations when `accuracy` is above that threshold.
