### ISSUE TITLE
Javascript in sample app crashes

### ISSUE THREAD

**Issue by johnhemming** [transistorsoft/cordova-background-geolocation-SampleApp#122]
Line 132 in
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/examples/cordova-basic/www/js/index.js

crashes:
 onToggleEnabled: function() {
        if (app.state.enabled) {
            app.bgGeo.stop(function(state) {
                console.log('- stop success');
                app.setState(state);
                app.setLabel('Stopped', 'grey');
            });
        } else {
----> this line            app.bgGeo.start(function(state) {
                console.log('- start success');
                app.setState(state);
                app.setLabel('Acquiring motionchange position...', 'red');
            });
        }
    },

Why?

What should I do to get it to work.   

If I need to change it to a promise in accordance with the documentation then what other obsolete code is there in the linked javascript?

**Comment by christocracy** [comment]
The /Cordova/basic app in this repo is out-dated.

See the plugin repo readme for simple implementation instructions.

**Comment by johnhemming** [comment]
Thanks.  Having put in the code in the readme I am getting the following crash:

--------- beginning of crash
01-02 13:04:48.732  4110  4254 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
01-02 13:04:48.732  4110  4254 E AndroidRuntime: Process: direct.vat.geo1, PID: 4110
01-02 13:04:48.732  4110  4254 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at java.lang.reflect.Method.getParameterTypes(Method.java:186)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:171)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:17)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.BootReceiver.a(Unknown Source:8)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.BootReceiver.a(Unknown Source:0)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at com.transistorsoft.locationmanager.BootReceiver$1.run(Unknown Source:104)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-02 13:04:48.732  4110  4254 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)

**Comment by christocracy** [comment]
Do **not** use the Cordova app in this repo.

Generate **your own** with the Cordova CLI.  **then** use the code from the README.

**Comment by johnhemming** [comment]
Thank you for your help with this.  The plugin is now talking to my server.   My server does not understand it, but that is a different issue and one I can sort out.
