### ISSUE TITLE
Android - using emulator with route

### ISSUE THREAD

**Issue by johnhemming** [transistorsoft/cordova-background-geolocation-SampleApp#124]
It is possible using the emulator as part of Android Studio to specify a route.  However, when the phone is travelling this emulated route it does not get any responses from the plugin.  That could be because the plugin wants also to have some movement.    

Is there a mechanism that can be used to make the plugin respond in terms of location and geofences even when the only thing that is changing is the location or is there a problem in that this emulator debugging tool cannot be used?

**Comment by christocracy** [comment]
>However, when the phone is travelling this emulated route it does not get any responses from the plugin

The plugin uses ActivityRecognition API to determine when device is *moving* vs *stationary*.  The emulator doesn't cause this API to emit events so the plugin always thinks it's sitting still.

In emulator, you must manually tell the plugin to enter the *moving* state via `BackgroundGeolocation.changePace(true)`.

I never use the Android emulator, only real devices.  See plugin repo Wiki ["Debugging"](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging)

**Comment by johnhemming** [comment]
Thank you for this.   As a matter of interest using the emulator with routes and change pace does cause the geofences to trigger.  Your note on debugging indicates that  Lockito does not.

**Comment by christocracy** [comment]
Geofences *sometimes.* fire with Lockito.  It’s hit and miss.
