### ISSUE TITLE
Data is not reaching to server on App Terminate

### ISSUE THREAD

**Issue by venujakku** [transistorsoft/cordova-background-geolocation-SampleApp#127]
Hi, 

Data is not reaching to server on App Terminate. 

Where should I add our code to reach data into our server even on app Terminate?

**Comment by christocracy** [comment]
Are you talking specifically about a problem with the SampleApp?

**Comment by venujakku** [comment]
Yes

**Comment by christocracy** [comment]
Have you read the Philosophy of Operation at the plugin Github repo?

Have you read the API docs Config.stopOnTerminate?  The api docs will explain the differences in behavior between iOS and Android.

You’ve not even specified iOS or Android.

**Comment by venujakku** [comment]
Hi,
how should send data to the server
![ServerSideImplimentation](https://user-images.githubusercontent.com/4727081/88451029-355af080-ce71-11ea-81af-9b09e9d69426.JPG) this is my Server Side implimention. 
![AppSideImplimentationWithKey](https://user-images.githubusercontent.com/4727081/88451042-5ae7fa00-ce71-11ea-8875-c3c4004a4f97.JPG)  This is my App Side (Client) implimentation. we have license So we implimented separe App.

**Comment by christocracy** [comment]
> Data is not reaching to server on App Terminate

Is your issue solved?  The SampleApp repo is not the place for questions like this.

Technical questions about the plugin should be handled at the plugin repo.
