### ISSUE TITLE
background is stopped

### ISSUE THREAD

**Issue by jsvinueza** [transistorsoft/cordova-background-geolocation-SampleApp#128]
Hello

I need your support

We have developed an app with ionic and cordova for android 10. In this App we have implemented background transistorsoft. 

1. The app contains 2 views
2. In the view main activates the background and here is fine.
3. Then we navigate to the another view and the phone is turn off the display. The background is still sending positions to the server.
4. After I turn on the display and I return to the view main, then the background is stopped.

Please help me

**Comment by christocracy** [comment]
This is the repo for the SampleApp, not *the plugin*
