### ISSUE TITLE
failing to build sample app in Xcode

### ISSUE THREAD

**Issue by icepicknz** [transistorsoft/cordova-background-geolocation-SampleApp#131]
See attached screenshot.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/9022948/107579433-01eb8200-6c5a-11eb-9f75-01b2e2680c25.png">

**Comment by christocracy** [comment]
are you sure you followed all the *Setup Steps* at the README?

**Comment by icepicknz** [comment]
yup
git clone https://github.com/transistorsoft/cordova-background-geolocation-SampleApp.git
cd cordova-background-geolocation-SampleApp
npm install -g cordova ionic

ionic cordova prepare iOS
ionic cordova run ios --emulator

I saw in another post to maybe try this...

Barrys-MacBook-Pro:ios barrymurphy$ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
Barrys-MacBook-Pro:ios barrymurphy$

**Comment by christocracy** [comment]
Are you opening in XCode the .xcodeproject or .xcworkspace?

**Comment by christocracy** [comment]
Also, what is your `$ cordova platform`?

**Comment by icepicknz** [comment]
I tried a whole bunch of things, in the end I deleted the iOS folder, started from scratch and now its working; I must have been missing some items 

all fixed thanking you
