### ISSUE TITLE
Not able to build success on devices using Xcode7.0

### ISSUE THREAD

**Issue by hrpatidar** [transistorsoft/cordova-background-geolocation-SampleApp#18]
Hi Chris,

I am using free version for iOS devices. It was working fine with earlier version of Xcode and iOS. And I am able to build cordova app on iOS devices. 

But with latest version of Xocde7.0 and iOS9, I am not able to build on devices due to some backround-geolocation plugin issues. If I removed geolocation plugin then Xcode is able to build on devices. Please refer attached screen shot. 

Please guide me and let me know if something I am doing wrong. 

Thanks

![reference1](https://cloud.githubusercontent.com/assets/7664377/10278973/4ed31c54-6b7f-11e5-99ba-db42125a4f04.png)
![reference2](https://cloud.githubusercontent.com/assets/7664377/10278972/4ed34a58-6b7f-11e5-8b88-e877114661da.png)

**Comment by christocracy** [comment]
Remove / re-install the plugin.  Destroy / re-add your iOS platform.

I'm using Xcode 7 here of course.  I fixed this issue already

On Monday, October 5, 2015, hrpatidar <notifications@github.com> wrote:

> Hi Chris,
>
> I am using free version for iOS devices. It was working fine with earlier
> version of Xcode and iOS. And I am able to build cordova app on iOS
> devices.
>
> But with latest version of Xocde7.0 and iOS9, I am not able to build on
> devices due to some backround-geolocation plugin issues. If I removed
> geolocation plugin then Xcode is able to build on devices. Please refer
> attached screen shot.
>
> Please guide me and let me know if something I am doing wrong.
>
> Thanks
>
> [image: reference1]
> <https://cloud.githubusercontent.com/assets/7664377/10278973/4ed31c54-6b7f-11e5-99ba-db42125a4f04.png>
> [image: reference2]
> <https://cloud.githubusercontent.com/assets/7664377/10278972/4ed34a58-6b7f-11e5-8b88-e877114661da.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/18>
> .
>


-- 
Snet form Gmail Mobile

**Comment by hrpatidar** [comment]
Great. I have deleted all the files and re-installed again and I am able to build now on iOS devices. Thanks a lot. 

But Facing so many warnings. What is the reason behind this. See screen shots.  

![screen shot 2015-10-05 at 4 55 37 pm](https://cloud.githubusercontent.com/assets/7664377/10279324/6a7d099e-6b82-11e5-9840-b5be3eb5ea99.png)
![screen shot 2015-10-05 at 4 56 04 pm](https://cloud.githubusercontent.com/assets/7664377/10279325/6a821d76-6b82-11e5-9a32-aed9e4d647c4.png)

**Comment by christocracy** [comment]
In you app, set the minimum version to iOS 7 and warnings go away.  Cordova
default is iOS 6

My framework was built for min iOS 7.

On Monday, October 5, 2015, hrpatidar <notifications@github.com> wrote:

> Great. I have deleted all the files and re-installed again and I am able
> to build now on iOS devices. Thanks a lot.
>
> But Facing so many warnings. What is the reason behind this. See screen
> shots.
>
> [image: screen shot 2015-10-05 at 4 55 37 pm]
> <https://cloud.githubusercontent.com/assets/7664377/10279324/6a7d099e-6b82-11e5-9840-b5be3eb5ea99.png>
> [image: screen shot 2015-10-05 at 4 56 04 pm]
> <https://cloud.githubusercontent.com/assets/7664377/10279325/6a821d76-6b82-11e5-9a32-aed9e4d647c4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/18#issuecomment-145501581>
> .
>


-- 
Snet form Gmail Mobile
