### ISSUE TITLE
SampleApp is just terminated on the android device. 

### ISSUE THREAD

**Issue by muphy** [transistorsoft/cordova-background-geolocation-SampleApp#20]
My phone is Nexus 5. I bought a premium version last night.
I built successfully my ionic app based on SampleApp. I just modified widget id and appended licence value and orderId value from you.
When I ran my app in my device nexus5 with typing "cordova run" in the command line, the app is shut down .
And I have debugged my app with "adb logcat" and I received below error messages in the console.
```
11-17 16:01:19.702 19065 19065 I TSLocationManager: - PRUNE -1days
11-17 16:01:19.723 19065 19065 I TSLocationManager: - GooglePlayServices connected
11-17 16:01:19.732 19065 19065 D AndroidRuntime: Shutting down VM
11-17 16:01:19.733 19065 19065 E AndroidRuntime: FATAL EXCEPTION: main
11-17 16:01:19.733 19065 19065 E AndroidRuntime: Process: xyz.zolywood.gpstracker.ionic, PID: 19065
11-17 16:01:19.733 19065 19065 E AndroidRuntime: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
11-17 16:01:19.733 19065 19065 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1599)
11-17 16:01:19.733 19065 19065 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1552)
```
So I built your SampleApp but I had received same error messages.

I wondered if ACCESS_FINE_LOCATION permission was not appended, so I opened config.xml file and androidmanifest.xml file. All permissions were appended. 

How can I solve this problem?

thanks.

**Comment by christocracy** [comment]
Will look first thing today.

Ihe plugin automatically adds required permissions

On Tuesday, November 17, 2015, JongAm Oh <notifications@github.com> wrote:

> My phone is Nexus 5. I bought a premium version last night.
> I built successfully my ionic app based on SampleApp. I just modified
> widget id and appended licence value and orderId value from you.
> When I ran my app in my device nexus5 with typing "cordova run" in the
> command line, the app is shut down .
> And I have debugged my app with "adb logcat" and I received below error
> messages in the console.
>
> 11-17 16:01:19.702 19065 19065 I TSLocationManager: - PRUNE -1days
> 11-17 16:01:19.723 19065 19065 I TSLocationManager: - GooglePlayServices connected
> 11-17 16:01:19.732 19065 19065 D AndroidRuntime: Shutting down VM
> 11-17 16:01:19.733 19065 19065 E AndroidRuntime: FATAL EXCEPTION: main
> 11-17 16:01:19.733 19065 19065 E AndroidRuntime: Process: xyz.zolywood.gpstracker.ionic, PID: 19065
> 11-17 16:01:19.733 19065 19065 E AndroidRuntime: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
> 11-17 16:01:19.733 19065 19065 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:1599)
> 11-17 16:01:19.733 19065 19065 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:1552)
>
> So I built your SampleApp but I had received same error messages.
>
> I wondered if ACCESS_FINE_LOCATION permission was not appended, so I
> opened config.xml file and androidmanifest.xml file. All permissions were
> appended.
>
> How can I solve this problem?
>
> thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/20>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Are you forgetting to execute "`build`"?

```
$ cordova build android
$ cordova run android
```

**Comment by christocracy** [comment]
Also, what version Cordova?

**Comment by christocracy** [comment]
Or maybe you've got the free version installed?  Whenever installing a new version of **any** plugin, you **must** remove the previous version first.

@see ["When in Doubt..."](https://github.com/transistorsoft/cordova-background-geolocation/wiki/Help-it-Doesn't-Work!!#when-in-doubt-remove--re-install-the-plugin-and-platform)

**Comment by muphy** [comment]
ionic version is maybe 1.7.5.  and I didn't forget order of the build and run command. I am home now. my home pc is window 7. my office pc is mac.

**Comment by muphy** [comment]
I will rebuild the sampleapp in my home pc. and I will be touch with you.

**Comment by christocracy** [comment]
update?
