### ISSUE TITLE
Post Additional data to server

### ISSUE THREAD

**Issue by Bwade** [transistorsoft/cordova-background-geolocation-SampleApp#21]
I need to POST additional data to my server and I was struggling on were I would add the extra data in context to the Sample app. Can you provide any guidance with the "extras" parameters that can be passed in the getCurrentPosition function? I see the following:
```javascript
getCurrentPosition: function(callback, failure, options) {
            // options = window.localStorage.getItem('device')
            if ($plugin) {
                $plugin.getCurrentPosition(callback, failure, options);
            }
        },
```
How would I add my extra parameters? Your assistance is greatly appreciated.

**Comment by christocracy** [comment]
In the [API docs](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#getcurrentpositionsuccessfn-failurefn-options), of course

**Comment by Bwade** [comment]
Of course the API docs! Who would think to look there!

I do see the following in the Settings Controller:
```javascript
  $scope.centerOnMe = function () {
    if (!$scope.map) {
      return;
    }

    BackgroundGeolocationService.getCurrentPosition(function(location, taskId) {
      $scope.map.setCenter(new google.maps.LatLng(location.coords.latitude, location.coords.longitude));
      $scope.setCurrentLocationMarker(location);
      BackgroundGeolocationService.finish(taskId);
    }, function(error) {
      console.error("- getCurrentPostion failed: ", error);
    }, {
      maximumAge: 0
    });
  };
```

When I modify the function like so:
```javascript
$scope.centerOnMe = function () {
    if (!$scope.map) {
      return;
    }

    BackgroundGeolocationService.getCurrentPosition(function(location, taskId) {
      $scope.map.setCenter(new google.maps.LatLng(location.coords.latitude, location.coords.longitude));
      $scope.setCurrentLocationMarker(location);
      var device = window.localStorage.getItem('device');
      BackgroundGeolocationService.finish(taskId);
    }, function(error) {
      console.error("- getCurrentPostion failed: ", error);
    }, {
      maximumAge: 0,
      extra: {
        'device': device,
        'foo': 'bar' 
      }
    });
  };
```
I see the following in my Console
```
[js] onMotionChange:  false {"is_moving":false,"timestamp":"2015-11-17T20:02:22.043Z","uuid":"e9e4d0ef-469a-4bfb-b513-00e2c9759aec","coords":{"longitude":-90.3353283,"latitude":38.6489996,"accuracy":30,"speed":0,"heading":0,"altitude":0},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":0.38999998569488525},"extras":{}} 
```
As you can see extra is empty.

is there a way to test what exactly is being sent to the server?

**Comment by christocracy** [comment]
1.  You're looking for your `extras` in the `onMotionChange` handler.  They won't be there.  The `extras` are only posted in the single location retrieved by `getCurrentPosition`.

2.  The name is `extras` (plural) -- not `extra` (singular). [extras](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-object-extras)

3.  However, I don't think the `extras` are echoed back to your Javascript callback.  You can be sure that if you provide `extras` to `getCurrentPosition, they are most certainly posted to your server.

**Comment by christocracy** [comment]
And btw, if you're looking to `POST` Device info to your server, since this information is basically **CONSTANT** data, you've be better off adding that to the plugin's [#params](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-object-params) config.

```javascript
bgGeo.configure(success, fail, {
  .
  .
  .
  params: {
    device: window.localStorage.getItem('device')
  }
});
```

I do this in the SampleApp [here](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/services.js#L267)

**Comment by Bwade** [comment]
Thanks for all the help!
