### ISSUE TITLE
Passing header to server

### ISSUE THREAD

**Issue by Bwade** [transistorsoft/cordova-background-geolocation-SampleApp#22]
Chris,

I had a quick question about passing headers in the demo app. From my understanding, or lack thereof, of the documentation I need to set the 'headers in the "configurePlugin" of the demo app. Here is my current set up:

```javascript
configurePlugin: function (bgGeoPlugin) {
			//Get Basic Device Information
			var device = ionic.Platform.device();
			$platform = device.platform;

			var me = this;
			var config = this.getConfig();
			config.params = config.params || {
				};

			$plugin = bgGeoPlugin;

			// Configure BackgroundGeolocation Plugin
			$plugin.configure(fireLocationListeners, function (error) {
				console.warn('BackgroundGeolocation Error: ' + error);
			}, config);


			var deviceObj = {
				'imeiEsn': window.localStorage.getItem('imei'),
				'phoneNumber': window.localStorage.getItem('phoneNumber')
			};

			deviceObj['device'] = device;

			config.params.device = deviceObj;
			config.headers = {
				"API-Key": "XXXXXXXXXXXXXXXXX"
			};
			window.localStorage.setItem('device', JSON.stringify(config.params.device));
			
			if (this.getEnabled()) {
				$plugin.start();
			}
		},
```
I am passing the header as 
```javascript
 config.headers = {
				"API-Key": "XXXXXXXXXXXXXXXXX"
			};
```
I don't think this is correct and was curious if you could provide a little guidance.

Thanks in advance.

**Comment by christocracy** [comment]
Looks fine.

On Tue, Dec 8, 2015 at 8:44 AM, Robert Wade <notifications@github.com>
wrote:

> Chris,
>
> I had a quick question about passing headers in the demo app. From my
> understanding, or lack thereof, of the documentation I need to set the
> 'headers in the "configurePlugin" of the demo app. Here is my current set
> up:
>
> configurePlugin: function (bgGeoPlugin) {
>             //Get Basic Device Information
>             var device = ionic.Platform.device();
>             $platform = device.platform;
>
>             var me = this;
>             var config = this.getConfig();
>             config.params = config.params || {
>                 };
>
>             $plugin = bgGeoPlugin;
>
>             // Configure BackgroundGeolocation Plugin
>             $plugin.configure(fireLocationListeners, function (error) {
>                 console.warn('BackgroundGeolocation Error: ' + error);
>             }, config);
>
>
>             var deviceObj = {
>                 'imeiEsn': window.localStorage.getItem('imei'),
>                 'phoneNumber': window.localStorage.getItem('phoneNumber')
>             };
>
>             deviceObj['device'] = device;
>
>             config.params.device = deviceObj;
>             config.headers = {
>                 "API-Key": "XXXXXXXXXXXXXXXXX"
>             };
>             window.localStorage.setItem('device', JSON.stringify(config.params.device));
>
>             if (this.getEnabled()) {
>                 $plugin.start();
>             }
>         },
>
> I am passing the header as
> '''javascript
> config.headers = {
> "API-Key": "XXXXXXXXXXXXXXXXX"
> };
>
> I don't think this is correct and was curious if you could provide a little guidance.
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/22>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
