### ISSUE TITLE
GeoLocation not working on ios

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-SampleApp#24]
Hello,

I tried installing this application, and the geolocation is not working.  It never asks me for my location, and when I click the locate icon in the bottom left corner, it does not take me to my current location.  I have the switch in the top right set to on.  What am I doing wrong?  (I am on ios 8).

Thanks!

**Comment by christocracy** [comment]
That is very odd.  Show me the logs of your app booting.

**Comment by dtruel** [comment]
Output from xcode device console

Jan 15 11:41:43 My-iPhone kernel[0] <Notice>: xpcproxy[1604] Container: /private/var/mobile/Containers/Data/Application/59070709-DABB-42F8-8C5A-51E568F3FF1E (sandbox)
Jan 15 11:41:43 My-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Jan 15 11:41:43 My-iPhone BG Geo[1604] <Error>: assertion failed: 12F70: libxpc.dylib + 51923 [89A85F22-6D73-33D8-9D7A-FCF58D58C58E]: 0x7d
Jan 15 11:41:43 My-iPhone Unknown[1604] <Error>: 
Jan 15 11:41:43 My-iPhone BG Geo[1604] <Notice>: DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/59070709-DABB-42F8-8C5A-51E568F3FF1E/Library/Cookies/Cookies.binarycookies
Jan 15 11:41:43 My-iPhone BG Geo[1604] <Warning>: Apache Cordova native platform version 3.8.0 is starting.
Jan 15 11:41:43 My-iPhone BG Geo[1604] <Warning>: Multi-tasking -> Device: YES, App: YES
Jan 15 11:41:43 My-iPhone BG Geo[1604] <Warning>: Unlimited access to network resources
Jan 15 11:41:44 My-iPhone BG Geo[1604] <Warning>: [CDVTimer][keyboard] 0.547945ms
Jan 15 11:41:44 My-iPhone BG Geo[1604] <Warning>: [CDVTimer][splashscreen] 382.224977ms
Jan 15 11:41:44 My-iPhone BG Geo[1604] <Warning>: [CDVTimer][TotalPluginStartup] 385.010958ms
Jan 15 11:41:44 My-iPhone BG Geo[1604] <Warning>: Resetting plugins due to page load.
Jan 15 11:41:47 My-iPhone BG Geo[1604] <Warning>: Finished load of: file:///private/var/mobile/Containers/Bundle/Application/08D87CDE-ADCD-4362-B7BC-F4566E351DE8/BG%20Geo.app/www/index.html#/
Jan 15 11:41:50 My-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Jan 15 11:41:50 My-iPhone BG Geo[1604] <Warning>: WARN: Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

**Comment by christocracy** [comment]
I don't see anything from my plugin in there.  Are you sure you followed *every* step of the [installation instructions](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp#installation), **especially** steps **2** & **3**?

**Comment by dtruel** [comment]
Ok think I found the error. I did not use sudo with step 2 or 3 and so was not working right.  However, I have a new error when I build.

The following build commands failed:
	Ld build/emulator/BG\ Geo.app/BG\ Geo normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/MAMP/htdocs/background-location/platforms/ios/cordova/build-debug.xcconfig,-project,BG Geo.xcodeproj,ARCHS=i386,-target,BG Geo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Applications/MAMP/htdocs/background-location/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/MAMP/htdocs/background-location/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Applications/MAMP/htdocs/background-location/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Applications/MAMP/htdocs/background-location/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
