### ISSUE TITLE
Default app not POSTing to server - but accesses url

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-SampleApp#25]
Hello,

I managed to get the sample app installed -- after figuring out I needed to update XCode.  It seems to be recording its location just fine.  However, it is not sending its location to the test server I set up.  So to do another test, an associate of mine wrote a script that logs all get and post requests to the server.  It was accessing the URL, but there was nothing contained in the Get or POST php arrays.  Do you know why this might be?

(Note this is with it set to POST to the server)

**Comment by christocracy** [comment]
Search all issues for "[php](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues?utf8=%E2%9C%93&q=php)"

PHP is dumb.  
https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/2
