### ISSUE TITLE
Docs for settings?

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-SampleApp#26]
Hello,

There are a ton of settings for the app - how do I know what they all mean?  Do I just use the api docs below, or do you have something specific for the app?

https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md

Thanks!

**Comment by christocracy** [comment]
Yes, that's the docs.  You should glance quickly through each config setting.  Start with the example in README (which includes pretty much every setting.  Start with that and whittle-out what you aren't interested in as you become familiar with what they do.

There are 4 groups:
- Geolocation settings
- Activity Recognition settings
- HTTP Settings
- Application settings.

The most important are:

```
  debug: true,
  desiredAccuracy: 0,
  distanceFilter: 50,
  activityRecognitionInterval: 10000,
  stopTimeout: 5,  // <-- 5 is nice for iOS; 0 is fine for Android
  // iOS
  stationaryRadius: 50
```

**Comment by dtruel** [comment]
Thank you
