### ISSUE TITLE
Prenium repo 404

### ISSUE THREAD

**Issue by sadortun** [transistorsoft/cordova-background-geolocation-SampleApp#27]
FYI

Your url to prenium repo gives a 404 in `https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/README.md`
```
A. Premium Version (requires paid license)
$ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git
```

**Comment by christocracy** [comment]
The url to premium url doesn't report 404 if you purchase a license.  It's
a private repo.

On Tuesday, January 26, 2016, sadortun <notifications@github.com> wrote:

> FYI
>
> Your url to prenium repo gives a 404 in
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/README.md
>
> A. Premium Version (requires paid license)
> $ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/27>
> .
>


-- 
Snet form Gmail Mobile

**Comment by sadortun** [comment]
I was expecting a 403 but i Found this in the GIthub Docs


> Typically, we send a 404 error when your client isn't properly authenticated. You might expect to see a 403 Forbidden in these cases. However, since we don't want to provide any information about private repositories, the API returns a 404 error instead.


https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists

**Comment by christocracy** [comment]
Precisely. I get 404 on my own repos if I logout of my github account.

I suggest you purchase a license so you don't have this problem ;)

On Tuesday, January 26, 2016, sadortun <notifications@github.com> wrote:

> I was expecting a 403 but i Found this in the GIthub Docs
>
> Typically, we send a 404 error when your client isn't properly
> authenticated. You might expect to see a 403 Forbidden in these cases.
> However, since we don't want to provide any information about private
> repositories, the API returns a 404 error instead.
>
>
> https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/27#issuecomment-175386781>
> .
>


-- 
Snet form Gmail Mobile

**Comment by sadortun** [comment]
License indeed :)  Sadly, I have almost no time in the next month, and I am looking for manpower to develop part of app before end of Febuary. 

If you know a good dev that have some spare time, let me know !  Or if you want to do a "special offer" that include the license, and my custom app :) That would be great :+1:
