### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Leomhl** [transistorsoft/cordova-background-geolocation-SampleApp#28]
Alert: Failed to change pace: Class not found  :/

**Comment by christocracy** [comment]
Do you have a license for Android?

**Comment by svnindia** [comment]
I am also getting the same issue.. license for Android ?

cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git

**Comment by christocracy** [comment]
Have you *purchased* [a license](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium)?

**Comment by svnindia** [comment]
No, Cant we try the free version

**Comment by christocracy** [comment]
You can only try free **iOS**.  To demo Android, install the plugin from [Play Store](https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic).

There is no free Android or Android trial.

**Comment by svnindia** [comment]
Demo video available for how to use apps ?

**Comment by christocracy** [comment]
Working on it.  Nothing yet.

On Thu, Feb 11, 2016 at 1:51 PM, sanjithkumar venkatesan <
notifications@github.com> wrote:

> Demo video available for how to use apps ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/28#issuecomment-183008310>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
