### ISSUE TITLE
Help when using Firebase as backend 

### ISSUE THREAD

**Issue by BrentDietrich** [transistorsoft/cordova-background-geolocation-SampleApp#3]
Hi Chris, 

I'm trying to use <a href="https://www.firebase.com/" target="_blank">Firebase</a> for my backend. They provide a javascript api and prefer not to use traditional client/server protocols.

Using your SampleApp, I've been able to post GPS coords to Firebase when changePace is true. Otherwise, when changePace is false, Firebase only receives the initial BackgroundGeolocation but does not update when the device moves. Markers are plotted and everything appears to be working on the plugin/app but without the firebase call. 

Any tips or information would definitely help my development. Thank you in advance.

**Comment by christocracy** [comment]
When you say "does not update when the device moves", how far is the device moving?

Are you testing with simulator, and setting `iOS Simulator->Debug->Location->City Drive`?

**Comment by BrentDietrich** [comment]
I've been running a 500 foot route around the office with my iPhone (app installed) in hand. When changePace is true, the Firebase api runs and all coords are recorded. When changePace is false, only the initial coord is recorded.

**Comment by christocracy** [comment]
It’s probably not far enough.  500 feet is about 150 meters.  I typically
have to travel 200 meters to trigger a “stationary exit”.

Keep walking until it triggers.  Do not turn back.  It will trigger.

On Fri, Jun 26, 2015 at 12:38 PM, BrentDietrich <notifications@github.com>
wrote:

> I've been running a 500 foot route around the office with my iPhone (app
> installed) in hand. When changePace is true, the Firebase api runs and all
> coords are recorded. When changePace is false, only the initial coord is
> recorded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/3#issuecomment-115748810>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by BrentDietrich** [comment]
I'll give it try.
