### ISSUE TITLE
System specs for building sample app

### ISSUE THREAD

**Issue by tacman** [transistorsoft/cordova-background-geolocation-SampleApp#30]
Can you please modify the instructions for building the sample app to include recommended versions of the tools necessary to build?

* ionic
* xcode
* Mac OS (Yosemite?  El Capitan)
* Cordova

**Comment by christocracy** [comment]
- Ionic doesn't matter.
- latest Xcode
- Mac OS doesn't matter
- Cordova 4+

On Monday, February 15, 2016, tacman <notifications@github.com> wrote:

> Can you please modify the instructions for building the sample app to
> include recommended versions of the tools necessary to build?
>
>    - ionic
>    - xcode
>    - Mac OS (Yosemite? El Capitan)
>    - Cordova
>
> The instructions include a reference to ionic keyboard
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/30>
> .
>


-- 
Snet form Gmail Mobile
