### ISSUE TITLE
12 Duplicate symbols for architecture i386 ERROR ** build failed ** OSX

### ISSUE THREAD

**Issue by ontwikkelfabriek** [transistorsoft/cordova-background-geolocation-SampleApp#31]
I try to build the IOS Sample App and encounter an error. I followed the tutorial to the letter. When I execute the 'cordova build ios' command I get the following error: 'ld: 12 duplicate symbols for architecture i386'
![error](https://cloud.githubusercontent.com/assets/9429959/13071737/a9137892-d495-11e5-99ef-607de7f5e924.png)

**Comment by christocracy** [comment]
Are you using the latest Xcode?  If not, upgrade.

On Tuesday, February 16, 2016, ontwikkelfabriek <notifications@github.com>
wrote:

> I try to build the IOS Sample App and encounter an error. I followed the
> tutorial to the letter. When I execute the 'cordova build ios' command I
> get the following error: 'ld: 12 duplicate symbols for architecture i386'
> [image: error]
> <https://cloud.githubusercontent.com/assets/9429959/13071737/a9137892-d495-11e5-99ef-607de7f5e924.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/31>
> .
>


-- 
Snet form Gmail Mobile

**Comment by ontwikkelfabriek** [comment]
I upgraded from 6.4 to 7.2.1  and it solved the issue.

**Comment by christocracy** [comment]
Always, always use latest Xcode.

On Wednesday, February 17, 2016, ontwikkelfabriek <notifications@github.com>
wrote:

> I upgraded from 6.4 to 7.2.1 and it solved the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/31#issuecomment-185103077>
> .
>


-- 
Snet form Gmail Mobile
