### ISSUE TITLE
Issue when installing sample application 

### ISSUE THREAD

**Issue by SurviveDrive** [transistorsoft/cordova-background-geolocation-SampleApp#33]
Hi ,

Having an issue with this line I think.

$ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git

Can't find the plugin from this line  this line.

APPLEs-MacBook-Pro-2:cordova-background-geolocation-SampleApp UltimateCoder$ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git
Fetching plugin "https://github.com/transistorsoft/cordova-background-geolocation.git" via git clone
Username for 'https://github.com': SurviveDrive
Password for 'https://SurviveDrive@github.com': 
Error: Failed to fetch plugin https://github.com/transistorsoft/cordova-background-geolocation.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/jt/36vk3byn5g719m5c7qtmcw7c0000gn/T/git/1456447175107'...
remote: Repository not found.
fatal: repository 'https://github.com/transistorsoft/cordova-background-geolocation.git/' not found

Hope this is enough info 

Kind regards
Kingsley Mitchell

**Comment by christocracy** [comment]
You haven't yet accepted the invitation from Github to access the repo.
Check your mail and respond.

On Thursday, February 25, 2016, SurviveDrive <notifications@github.com>
wrote:

> Hi ,
>
> Having an issue with this line I think.
>
> $ cordova plugin add
> https://github.com/transistorsoft/cordova-background-geolocation.git
>
> Can't find the plugin from this line this line.
>
> APPLEs-MacBook-Pro-2:cordova-background-geolocation-SampleApp
> UltimateCoder$ cordova plugin add
> https://github.com/transistorsoft/cordova-background-geolocation.git
> Fetching plugin "
> https://github.com/transistorsoft/cordova-background-geolocation.git" via
> git clone
> Username for 'https://github.com': SurviveDrive
> Password for 'https://SurviveDrive@github.com':
> Error: Failed to fetch plugin
> https://github.com/transistorsoft/cordova-background-geolocation.git via
> git.
> Either there is a connection problems, or plugin spec is incorrect:
> Error: git: Command failed with exit code 128 Error output:
> Cloning into
> '/var/folders/jt/36vk3byn5g719m5c7qtmcw7c0000gn/T/git/1456447175107'...
> remote: Repository not found.
> fatal: repository '
> https://github.com/transistorsoft/cordova-background-geolocation.git/'
> not found
>
> Hope this is enough info
>
> Kind regards
> Kingsley Mitchell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/33>
> .
>


-- 
Snet form Gmail Mobile

**Comment by SurviveDrive** [comment]
Seems to have pulled it successfully, Thank you Chris. Will let you know if any other issues come up
