### ISSUE TITLE
Intermittent Permission Dialog Box on iOS Devices

### ISSUE THREAD

**Issue by hrpatidar** [transistorsoft/cordova-background-geolocation-SampleApp#35]
I have seen, when my app is triggering to init background geolocation service. In few seconds sometimes I got a dialog box on iOS devices. It says, '...access your Motion & Fitness Activity'. But This is not coming every time even I deleted the app and install it again. 

I have checked my application permissions in device settings, there are always toggle on for Motion & Fitness Activity even I didn't get permission dialog box while init background geolocation service.

Please clear me on which scenario it will ask for permission or not. 

And also can we modify the message when requesting the permission?

Thanks

**Comment by christocracy** [comment]
"Motion & Fitness" updates are used by the plugin to determine the current activity of the device, eg: `walking`, `running`, `in_vehicle`, etc.

You can disable this by configuring [disableMotionActivityUpdates: true](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-boolan-disablemotionactivityupdates-false).

You have no control over the message.

If you disable it, you won't receive the [#activity](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Data-Schema) data in the recorded location.
