### ISSUE TITLE
Plugin Needs Data Storage Permission For Marshmallow

### ISSUE THREAD

**Issue by FSchmitthammer** [transistorsoft/cordova-background-geolocation-SampleApp#36]
When we use the plugin on Marshmallow it requires Data Storage permission and it does not ask for it.  We are required to manually give it permission and the plugin should initiate the request when used.  This is so it can store all of the geolocation data in the SQLite database it uses.

**Comment by christocracy** [comment]
Please post plugin issues at the plugin repo.  This is the SampleApp repo.
