### ISSUE TITLE
Loading On Device Boot

### ISSUE THREAD

**Issue by FSchmitthammer** [transistorsoft/cordova-background-geolocation-SampleApp#37]
Is there any way to add any additional functions to be called during the processing that occurs whenever the device is running.  We would like to call some web service calls in the background that does not go away on device boot.  It appears that the geolocation does run a background process that loads geolocation data into the geolocation database.  Is there a way to add function/webservice calls during this processing?

If that is not available, is there you can explain how you are loading a Cordova/PhoneGap application in the background that survives a device reboot?

**Comment by christocracy** [comment]
Is this a question for the SampleApp specifically?  This repo is purely for the SampleApp.

**Comment by FSchmitthammer** [comment]
It is the sample app and the premium plug in.  If you would like me to
request this in the plug in, I can.

Please advise...

Regards,
Fred Schmitthammer
(562)307-0219
(623)258-4400

**Comment by christocracy** [comment]
Post an issue at the plugin.
