### ISSUE TITLE
Sample App loads fine on Simulator but Blank screen on IOS device

### ISSUE THREAD

**Issue by Wade-BuildOtto** [transistorsoft/cordova-background-geolocation-SampleApp#38]
It ask for location and notification, no problem but when it finally loads the main screen the headers body and footer are all blank, just the blue divide lines are visible.

I think it might have to do with access external resources like maps.googleapis.com where the simulator has open permissions but a device might now.

**Comment by christocracy** [comment]
I just did a fresh clone of SampleApp:  everything's good on Sim and iPhone 6s.
