### ISSUE TITLE
Android google play dependency

### ISSUE THREAD

**Issue by netwrkx** [transistorsoft/cordova-background-geolocation-SampleApp#39]
Sample App does not work on Android without google services

**Comment by christocracy** [comment]
Are you a customer?

**Comment by netwrkx** [comment]
Freemium user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Chris ScottSent: Tuesday, 5 April 2016 19:10To: transistorsoft/cordova-background-geolocation-SampleAppReply To: transistorsoft/cordova-background-geolocation-SampleAppCc: Adebowale SamsonSubject: Re: [transistorsoft/cordova-background-geolocation-SampleApp] Android google play dependency (#39)Are you a customer?

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by christocracy** [comment]
There is no Android for free version

**Comment by netwrkx** [comment]
Does the premium version rely on google play services to work                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Chris ScottSent: Wednesday, 6 April 2016 00:21To: transistorsoft/cordova-background-geolocation-SampleAppReply To: transistorsoft/cordova-background-geolocation-SampleAppCc: Adebowale SamsonSubject: Re: [transistorsoft/cordova-background-geolocation-SampleApp] Android google play dependency (#39)There is no Android for free version

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by christocracy** [comment]
Yes
