### ISSUE TITLE
Android App not requesting permissions (gps, ineternet, etc)

### ISSUE THREAD

**Issue by Damionmaster** [transistorsoft/cordova-background-geolocation-SampleApp#4]
Hi christocracy,

i successfully installed the new sample app on an Andoid 5 device. However when i triy to run the apk on a 4.x-device the installer does not ask for permissions.

What i am doing wrong?

Kind Ragards,
Christian

**Comment by christocracy** [comment]
In what manner do you expect the Android app to ask for permissions?

On Tuesday, June 30, 2015, Damionmaster <notifications@github.com> wrote:

> Hi christocracy,
>
> i successfully installed the new sample app on an Andoid 5 device. However
> when i triy to run the apk on a 4.x-device the installer does not ask for
> permissions.
>
> What i am doing wrong?
>
> Kind Ragards,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/4>
> .
>


-- 
Snet from Gmail Mobile
