### ISSUE TITLE
ios build issue

### ISSUE THREAD

**Issue by dmvaldman** [transistorsoft/cordova-background-geolocation-SampleApp#40]
Went through your ios building instructions and got this error after running `cordova build ios`. Any help would be appreciated

```
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogManager.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogManager.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.cmdline in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
duplicate symbol _llvm.embedded.module in:
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
    BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
ld: 14 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/BG\ Geo.app/BG\ Geo normal i386
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/cordova/build-debug.xcconfig,-project,BG Geo.xcodeproj,ARCHS=i386,-target,BG Geo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/build/sharedpch
```

**Comment by christocracy** [comment]
What version XCode?

On Sunday, April 24, 2016, David Valdman <notifications@github.com> wrote:

> Went through your ios building instructions and got this error. Any help
> would be appreciated
>
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationManager.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogManager.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLogManager.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.cmdline in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> duplicate symbol _llvm.embedded.module in:
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>     BG Geo/Plugins/com.transistorsoft.cordova.background-geolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> ld: 14 duplicate symbols for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>
> ** BUILD FAILED **
>
>
> The following build commands failed:
>     Ld build/emulator/BG\ Geo.app/BG\ Geo normal i386
> (1 failure)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/cordova/build-debug.xcconfig,-project,BG Geo.xcodeproj,ARCHS=i386,-target,BG Geo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/dmvaldman/Code/cordova-background-geolocation-SampleApp/platforms/ios/build/sharedpch
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/40>
>


-- 
Snet form Gmail Mobile

**Comment by dmvaldman** [comment]
XCode v6.4

**Comment by dmvaldman** [comment]
I'll update to the latest and try again

**Comment by christocracy** [comment]
It is certainly the problem.  Always keep Xcode updated to the latest
version.

On Sunday, April 24, 2016, David Valdman <notifications@github.com> wrote:

> XCode v6.4
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/40#issuecomment-214110579>
>


-- 
Snet form Gmail Mobile

**Comment by dmvaldman** [comment]
That was it. Thanks!
