### ISSUE TITLE
App not working after building it

### ISSUE THREAD

**Issue by sktech** [transistorsoft/cordova-background-geolocation-SampleApp#43]
I build this sample app for Android platform. The plugin is not working.

my adb logcat shows following error

"exec() call to unknown plugin: BackgroundGeolocation"

I had updated SDK Manager, tried with a fresh install. Downgraded to Cordova version 5. Still it is not working.
Please let me know what i am missing.

**Comment by christocracy** [comment]
This is not a native error.  This is a JavaScript error.  Clearly you did not follow the sample app installation steps exactly as documented in the README.

Boot the JavaScript dev console to observebjavascript errors.
