### ISSUE TITLE
background geolocation not working in lolipop 

### ISSUE THREAD

**Issue by balapkm** [transistorsoft/cordova-background-geolocation-SampleApp#44]
i have used the repo link which you have mailed me and when opening geolocation app in kitkat, it asked me to
update google play service. After updating google play services, the app works perfectly.

when opening the app in lollipop, it did not ask me to upgrade google play service and also the app could not able
to get location. the app throws permission denied error.

cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git

Following screen shot has kitkat OS with google play version  9.0.82 (it's working fine)..
![working](https://cloud.githubusercontent.com/assets/5486829/15649293/1e990a4c-268e-11e6-8258-4702a6a915c2.png)

Following screen shot has lollipop OS with google play version  9.0.83 (it's not working )
![not working](https://cloud.githubusercontent.com/assets/5486829/15649308/2e4a705c-268e-11e6-9287-4bed00db4ee2.png)

**Comment by christocracy** [comment]
Logs please (from `$ adb logcat`)

**Comment by balapkm** [comment]
It's working fine now thanks chris...
