### ISSUE TITLE
Non-consistent GpsCordinate on disableElasticity

### ISSUE THREAD

**Issue by sktech** [transistorsoft/cordova-background-geolocation-SampleApp#46]
Hi 
i tested this application from Google Platstore.
I changed following Settings.  
distanceFilter : 10
disableElasticity : true.

Now whenever i start i starts getting reading after 300-500m. Sometimes the tracking stops and does not give any cordinates after 10-12 km. Smetimes it works fine. 

Screen Shot 1, 2, 3
![img-20160602-wa0015](https://cloud.githubusercontent.com/assets/8659244/15826399/fc404e46-2c24-11e6-9e96-a78015af4041.jpg)

![img-20160602-wa0000](https://cloud.githubusercontent.com/assets/8659244/15826346/d13011b4-2c24-11e6-93e4-90c7fc690257.jpg)
![img-20160602-wa0020](https://cloud.githubusercontent.com/assets/8659244/15826366/e5a347e2-2c24-11e6-854e-9505feb2ca68.jpg)

See in the above images (1,2,3) cordinates are jumping not giving straight linear points.

Screenshot(4,5,6)
![img-20160602-wa0003](https://cloud.githubusercontent.com/assets/8659244/15826446/2d2dde74-2c25-11e6-87ac-089d4e007af2.jpg)
![img-20160602-wa0001](https://cloud.githubusercontent.com/assets/8659244/15826465/3af2653e-2c25-11e6-934c-23043848ff9e.jpg)
![img-20160602-wa0016](https://cloud.githubusercontent.com/assets/8659244/15826480/4e4fc59a-2c25-11e6-9310-5532112317e9.jpg)

In above images(4,5,6) the co-ordinates are not constant . They are not pinging afte 10m. When i start navigation from begining, it starts giving co-ordinates after 300-500m(sometimes after 1km)

I tested this app on same android model on three different vehicles(car, bus, bike) from same start and end point. They show different readings on diff vehicles.

The difference ranges from 300m -2km between app reading and actual reading.

Please let me know the solution as i want accuracy in it.

**Comment by sktech** [comment]
Please reply it is very urgent
need to buy the plugin after clarification

**Comment by christocracy** [comment]
I suggest you try build the SampleApp.  The version from Google Play is
very old.

the SampleApp contains a license key which will unlock Android available in
the npm version of the plugin:

https://github.com/transistorsoft/cordova-background-geolocation-SampleApp

On Mon, Jun 6, 2016 at 5:20 PM, Sunil Kumbhar <notifications@github.com>
wrote:

> Please reply it is very urgent
> need to buy the plugin after clarification
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-224092009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lxlmfbY7_V-pYzJwg12uneyOnnWUks5qJI8MgaJpZM4Iu_1d>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
It's very possible the problems are completely due to your network
environment and there's little that can be done.

On Mon, Jun 6, 2016 at 5:21 PM, Chris Scott <christocracy@gmail.com> wrote:

> I suggest you try build the SampleApp.  The version from Google Play is
> very old.
>
> the SampleApp contains a license key which will unlock Android available
> in the npm version of the plugin:
>
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp
>
> On Mon, Jun 6, 2016 at 5:20 PM, Sunil Kumbhar <notifications@github.com>
> wrote:
>
>> Please reply it is very urgent
>> need to buy the plugin after clarification
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-224092009>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAA6lxlmfbY7_V-pYzJwg12uneyOnnWUks5qJI8MgaJpZM4Iu_1d>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by sktech** [comment]
But it shows different reading for different vehicles at the same time. As i told we tested on 3 different vehicles(bus, car and bike). Weused same mobile model and same mobile network provider. So how can this be done.
Plz let me know what can be the solution. I want to buy the plugin and once tested need to extend it for 10 apps.

**Comment by christocracy** [comment]
You'll have to provide far more information than you are if you want help.

Like logs, device model, os.

On Wed, Jun 8, 2016 at 2:31 AM, Sunil Kumbhar <notifications@github.com>
wrote:

> But it shows different reading for different vehicles at the same time. As
> i told we tested on 3 different vehicles(bus, car and bike). Weused same
> mobile model and same mobile network provider. So how can this be done.
> Plz let me know what can be the solution. I want to buy the plugin and
> once tested need to extend it for 10 apps.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-224501263>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l2KW6g02QmczbSuhN02r226sLgujks5qJmG9gaJpZM4Iu_1d>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by christocracy** [comment]
And did you build the latest SampleApp?  The version from play services was
last published many months ago.  Much has changed since then.

On Wed, Jun 8, 2016 at 2:40 AM, Chris Scott <christocracy@gmail.com> wrote:

> You'll have to provide far more information than you are if you want help.
>
> Like logs, device model, os.
>
> On Wed, Jun 8, 2016 at 2:31 AM, Sunil Kumbhar <notifications@github.com>
> wrote:
>
>> But it shows different reading for different vehicles at the same time.
>> As i told we tested on 3 different vehicles(bus, car and bike). Weused same
>> mobile model and same mobile network provider. So how can this be done.
>> Plz let me know what can be the solution. I want to buy the plugin and
>> once tested need to extend it for 10 apps.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-224501263>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAA6l2KW6g02QmczbSuhN02r226sLgujks5qJmG9gaJpZM4Iu_1d>
>> .
>>
>
>
>
> --
> Chris Scott
> Transistor Software <http://www.transistorsoft.com>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by vahidreza** [comment]
@sktech hi, did you managed to solve the problem or what?
what was the result since last post of @christocracy

**Comment by vahidreza** [comment]
@christocracy  as you stated above i tried to build the app but at below step i get a 404 error not found!
cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation.git

**Comment by christocracy** [comment]
It's not a problem with the plugin.  It's due to network environment and/or device inconsistencies.

Native location services are like a tap of water.  The plugin allows you to set the desired heat (desiredAccuracy) and flow-rate (distanceFilter).  What comes out of the tap is completely up to a) network environment, (b) device hardware and (c) Google Play Services API.

**Comment by vahidreza** [comment]
@christocracy
The git url is giving not found too just click on the url and you'll see. Is it private or what?

About the water tap i agree but what is the reason of mentioned jumps ?

Is there any optimum setting to minimize faulty results?

Is there anyway so your plugin use multiple location sources to increase accuracy?

**Comment by christocracy** [comment]
If you want to use Android in your own app, you must purchase a license
(premium version).  Yes, it's a private repo.

The jumps are due to poor accuracy.  I've just completed a trip completely
around the entire island of Iceland with almost no jumps at all.

The optimum setting is desiredAccuracy: 0

On Sunday, June 26, 2016, vahidreza <notifications@github.com> wrote:

> @christocracy <https://github.com/christocracy>
> The git url is giving not found too just click on the url and you'll see.
> Is it private or what?
>
> About the water tap i agree but what is the reason of mentioned jumps ?
>
> Is there any optimum setting to minimize faulty results?
>
> Is there anyway so your plugin use multiple location sources to increase
> accuracy?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228623218>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lwuzuwUBakSyOGxSndSPnpc7NJmJks5qPutFgaJpZM4Iu_1d>
> .
>


-- 
Snet form Gmail Mobile

**Comment by vahidreza** [comment]
thanks for the reply
but there are some issues:

1- i have emailed you via your website about a way with which I can test
the product before buying and you said try the demo app. the demo app on
the other side has some issues and you have suggested on git to not try the
google store app and build it by our own to test the newset release. so how
can i test the demo app before buying the license?

2- i had an issue with the old one and want to know if it's a case in the
latest release or not. I had no internet connection and I turned on the BG
Geolocation in your app, tapped the play button and drove about 30Km s . I
checked the app when I arrived and nothing is shown in the app (an empty
map area with nothing on it), I then turned on the wifi and tested again,
still nothing. I killed the activity by using android's task manager (but
not the service and not force closing it) and relaunched it, the pause icon
is now in play mode and it is showing me my current location with no
previous data.

**Comment by christocracy** [comment]
The npm module contains a relatively recent version of android.  The SampleApp contains a key to unlock it.  You can build the sample app for android with npm module cordova-background-geolocation-lt

**Comment by vahidreza** [comment]
what about the second item. should I be worried?

**Comment by christocracy** [comment]
No you should not be worried.  Build the sample app for Android.

What android OS/device model are you using?

On Monday, June 27, 2016, vahidreza <notifications@github.com> wrote:

> what about the second item. should I be worried?
>
> On Mon, Jun 27, 2016 at 3:24 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > The npm module contains a relatively recent version of android. The
> > SampleApp contains a key to unlock it. You can build the sample app for
> > android with npm module cordova-background-geolocation-lt
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714231
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADkHzyv9pxDdosY12r685rFb_VywNWMKks5qP6vrgaJpZM4Iu_1d
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714894>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l4x7UR8zkyR-VWCgZe-fzI1Vji-fks5qP6y1gaJpZM4Iu_1d>
> .
>


-- 
Snet form Gmail Mobile

**Comment by vahidreza** [comment]
my android device is
android 6.0
LG V10 (H960A)

but since i need it to be run on any android device the model/version
should not be a limit for your plugin. is there any limitation?

**Comment by christocracy** [comment]
Android >= 4.3

On Monday, June 27, 2016, vahidreza <notifications@github.com> wrote:

> my android device is
> android 6.0
> LG V10 (H960A)
>
> but since i need it to be run on any android device the model/version
> should not be a limit for your plugin. is there any limitation?
>
>
> On Mon, Jun 27, 2016 at 3:29 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > No you should not be worried. Build the sample app for Android.
> >
> > What android OS/device model are you using?
> >
> > On Monday, June 27, 2016, vahidreza <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > what about the second item. should I be worried?
> > >
> > > On Mon, Jun 27, 2016 at 3:24 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > The npm module contains a relatively recent version of android. The
> > > > SampleApp contains a key to unlock it. You can build the sample app
> for
> > > > android with npm module cordova-background-geolocation-lt
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714231
> > > >,
> > > > or mute the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/ADkHzyv9pxDdosY12r685rFb_VywNWMKks5qP6vrgaJpZM4Iu_1d
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714894
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAA6l4x7UR8zkyR-VWCgZe-fzI1Vji-fks5qP6y1gaJpZM4Iu_1d
> > >
> > > .
> > >
> >
> >
> > --
> > Snet form Gmail Mobile
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228715250
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADkHz1thIf9loofNyhyy5_3qu4ChOpxIks5qP60lgaJpZM4Iu_1d
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228715740>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l8-hZeI1KK3ajbi5YJI-aY3j0EIfks5qP62_gaJpZM4Iu_1d>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I'm sure your device will work perfectly.

Use desiredAccuracy: 0 to ensure best possible location accuracy.  Anything
higher does not use GPS.

I'm returning from vacation today.  I'll be in the office tomorrow

On Monday, June 27, 2016, vahidreza <notifications@github.com> wrote:

> my android device is
> android 6.0
> LG V10 (H960A)
>
> but since i need it to be run on any android device the model/version
> should not be a limit for your plugin. is there any limitation?
>
>
> On Mon, Jun 27, 2016 at 3:29 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > No you should not be worried. Build the sample app for Android.
> >
> > What android OS/device model are you using?
> >
> > On Monday, June 27, 2016, vahidreza <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > what about the second item. should I be worried?
> > >
> > > On Mon, Jun 27, 2016 at 3:24 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > The npm module contains a relatively recent version of android. The
> > > > SampleApp contains a key to unlock it. You can build the sample app
> for
> > > > android with npm module cordova-background-geolocation-lt
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714231
> > > >,
> > > > or mute the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/ADkHzyv9pxDdosY12r685rFb_VywNWMKks5qP6vrgaJpZM4Iu_1d
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228714894
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAA6l4x7UR8zkyR-VWCgZe-fzI1Vji-fks5qP6y1gaJpZM4Iu_1d
> > >
> > > .
> > >
> >
> >
> > --
> > Snet form Gmail Mobile
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228715250
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADkHz1thIf9loofNyhyy5_3qu4ChOpxIks5qP60lgaJpZM4Iu_1d
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/46#issuecomment-228715740>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l8-hZeI1KK3ajbi5YJI-aY3j0EIfks5qP62_gaJpZM4Iu_1d>
> .
>


-- 
Snet form Gmail Mobile

**Comment by vahidreza** [comment]
tnx
I'll try to build the app and come back to you If i need help.
have fun.

**Comment by vahidreza** [comment]
hey I have build the app using phonegap uild based on your instructions but the app force closed just when I enabled the GPS tracking switch at top right of the main view.
The odd thing is when installing the app I saw no GPS related permissions listed.

I have attached the PGB build zip file which I've uploaded.
Can you check it and tell me if there is any problem regarding the config.xml or any other related item..

[appiNet.Mobile.phonegap.zip](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/files/335127/appiNet.Mobile.phonegap.zip)
