### ISSUE TITLE
Error: Could not resolve 'settings/forceReloadOnBoot' from state 'settings'

### ISSUE THREAD

**Issue by mtoo020** [transistorsoft/cordova-background-geolocation-SampleApp#47]
Please add a new state for forceReloadOnBoot.

**Comment by christocracy** [comment]
You can add any settings you wish in app/home/home.js in the
#configureBackgroundGeolocation method

On Tuesday, June 7, 2016, mtoo020 <notifications@github.com> wrote:

> Please add a new state for forceReloadOnBoot.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/47>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l-NBc9yHW4y29L30444USfWJwXj2ks5qJiVRgaJpZM4IwiFA>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mtoo020** [comment]
I mean, when I tap on forceReloadOnBoot in Settings, it doesn't bring up the "true/false" menu for me to choose from.
