### ISSUE TITLE
Could not detect BackgroundGeolocation API - happens from the first run after clone

### ISSUE THREAD

**Issue by kim0z** [transistorsoft/cordova-background-geolocation-SampleApp#48]
Hi,
I just did clone the project and then started the project, ionic serve, then I noticed this message in the console log of the browser:
Could not detect BackgroundGeolocation API

I did deploy on iOS and noticed the gps is not working, any idea how this service stopped working ?

Note: I cloned this projects days a ago and developed on top of it, then the I fced the same issue.

**Comment by christocracy** [comment]
Did you follow *all* the steps?

**Comment by christocracy** [comment]
[Installation Steps](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp#installation)

**Comment by kim0z** [comment]
I facing an issue installing:
https://github.com/transistorsoft/cordova-background-geolocation.git

could be it moved to: 
https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by christocracy** [comment]
Did you [purchase a license](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium)?

**Comment by christocracy** [comment]
There are 2 versions:
1.  Free iOS-only "Lite" version.  ie:  the `-lt` repo.
2.  Paid iOS + Android **Premium** version.  

Read the instructions carefully and choose which version to use.

**Comment by kim0z** [comment]
Sorry for your time, the project now works, even the other project that based on the same source code back to work, code be restart all Env, Thank you.
