### ISSUE TITLE
Licence Validation Failure Android

### ISSUE THREAD

**Issue by emoran** [transistorsoft/cordova-background-geolocation-SampleApp#53]
I just installed the app from the console, when I want to run it, the message "License Validation Failure" appear and the tracking it seems isn't working. is this an issue of the code or should I do something additional?. It only happen in my android device. Thanks

**Comment by christocracy** [comment]
Did you change *anything* in the `config.xml`, particularly the `<widget id .../>`?

**Comment by emoran** [comment]
Yes, it seems someone changed the package id.. probably was that. there is a way to use a different one?

**Comment by christocracy** [comment]
If you want demo Android, you must leave the `<widget id />` as-is.  The [license](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/config.xml#L12) is bound to the SampleApp's `<widget id />`.

You can change it only by [purchasing your own license](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium)

**Comment by vijayb** [comment]
@christocracy I'm now having the same issue as the above. The widget ID is the same and has not changed. We purchased a license key and that value hasn't changed either. I'm wondering if it has expired (although I thought we purchased a perpetual license)

**Comment by christocracy** [comment]
License keys do not expire and the license validator **never** fails.  It always a configuration issue on your end.

This is not the place to be posting license issues.  This is the sample app repo.

**Comment by vijayb** [comment]
Apologies. Please direct me to the correct place to post license issues.

**Comment by christocracy** [comment]
You should post issues at the plugin repo.  
- [Premium Repo](https://github.com/transistorsoft/cordova-background-geolocation) (if you have access)
- [Public repo](https://github.com/transistorsoft/cordova-background-geolocation-lt) (if you don't have access to above)
