### ISSUE TITLE
Run in Browser

### ISSUE THREAD

**Issue by confa** [transistorsoft/cordova-background-geolocation-SampleApp#55]
When I run the app sample via ionic in browser (ionic serve), window.BackgroundGeolocation is undefined. Does it mean that I can't test my app in browser since I installed this plugin? Is there any way to inject this variables not only for ios\android build, but for Web as well? Thank you.

**Comment by christocracy** [comment]
There is no `window.BackgroundGeolocation` in browser.

**Comment by christocracy** [comment]
Test in Simulator or device.
