### ISSUE TITLE
Sample app POSTs, then GETs ?

### ISSUE THREAD

**Issue by CraftedDevTeam** [transistorsoft/cordova-background-geolocation-SampleApp#57]
We have installed the sample app on a couple of phones - on one phone it POSTs to the posttestserver.com quite happily, on another phone it does a couple of initial POSTs, and then seems to revert to doing GETs (with no location information) instead. Is there a reason why it would use GETs when configured to POST ?
Thanks

**Comment by christocracy** [comment]
I don't think it's possible for the plugin to ever execute a `GET` request.

**Comment by CraftedDevTeam** [comment]
This is the folder we've pointed it to on posttestserver.com - 

http://posttestserver.com/data/2016/09/27/rlapp_matthew/

Like I say the first couple of entries are POSTs, the rest are GETs - is this an issue with posttestserver?
Thanks

**Comment by christocracy** [comment]
I have no idea who controls `posttestserver`.  Probably an issue there.

Why don't you build my [Simple Node Server](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp#simple-testing-server) and use it.  It's what I use for development.

![](https://www.dropbox.com/s/770xxbh73xgrh9w/Screenshot%202016-09-27%2009.31.11.png?dl=1)

**Comment by CraftedDevTeam** [comment]
Sorry - we've just discovered that someone here was browsing to the posttestserver.com URL on their machine causing the GETs to appear...
