### ISSUE TITLE
GPS Sensor inactive

### ISSUE THREAD

**Issue by Damionmaster** [transistorsoft/cordova-background-geolocation-SampleApp#6]
Hi there,

i installed the SampleApp on my Moto E (2nd Gen, Android Version 5.0.2) and it works without any problems. 

As I try to run the same apk on my Samsung Galaxy S III Neo (Android Version 4.4.2) the gps sensor is not activated. Even the GPS Icon in the status bar does not appear. 

I checked the sensor using Google Maps on the Galaxy S III Neo. I only experience this issue within the SampleApp.

I´m quite confused. Can you give me a hint whether i am doing something wrong?

Kind Regards,
Christian

**Comment by christocracy** [comment]
Any sounds?

Logs?

On Wednesday, August 12, 2015, Damionmaster <notifications@github.com>
wrote:

> Hi there,
>
> i installed the SampleApp on my Moto E (2nd Gen, Android Version 5.0.2)
> and it works without any problems.
>
> As I try to run the same apk on my Samsung Galaxy S III (Android Version
> 4.4.2) the gps sensor is not activated. I checked the sensor using Google
> Maps on the Galaxy S III. I only experience this issue within the SampleApp.
>
> I´m quite confused. Can you give me a hint whether i am doing something
> wrong?
>
> Kind Regards,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/6>
> .
>


-- 
Snet form Gmail Mobile
