### ISSUE TITLE
Build error: File path too long on Windows, keep below 240 characters

### ISSUE THREAD

**Issue by ReemaBegum** [transistorsoft/cordova-background-geolocation-SampleApp#60]
After installing plugin getting build errors 

1. C:\Users\Waseem\Documents\Visual Studio 2015\Projects\BackGroundMode\BackGroundMode\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Users\Waseem\Documents\Visual Studio 2015\Projects\BackGroundMode\BackGroundMode\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

Help me to resolve these error

**Comment by christocracy** [comment]
I [googled this](http://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters)
