### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ReemaBegum** [transistorsoft/cordova-background-geolocation-SampleApp#61]
Error code 1 for command: cmd with args: /s,/c,""C:\Users\Waseem\Documents\Visual Studio 2015\Projects\BackGroundMode\BackGroundMode\platforms\android\gradlew" cdvBuildDebug -b "C:\Users\Waseem\Documents\Visual Studio 2015\Projects\BackGroundMode\BackGroundMode\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

one more issue

**Comment by christocracy** [comment]
Duplicate #60.

**Comment by ReemaBegum** [comment]
Thank you .. Build is successfull
