### ISSUE TITLE
problem with geo location sample app

### ISSUE THREAD

**Issue by prabu6194** [transistorsoft/cordova-background-geolocation-SampleApp#65]
Hello sir,
After running this app showing license validation failure. what can i do?

**Comment by christocracy** [comment]
Have you purchased a license?

**Comment by christocracy** [comment]
You can build the app for DEBUG without a license.

**Comment by christocracy** [comment]
are you not seeing

>Running in evaluation mode

?

**Comment by lowr** [comment]
hello,
 i have the same problem (License Validation Failure BackgroundGeolocation is running in evaluation mode)

**Comment by christocracy** [comment]
Evaluation mode is completely normal if you haven't purchased a license key.
