### ISSUE TITLE
Problem with current location and controlling when to locate the user

### ISSUE THREAD

**Issue by Hudhud** [transistorsoft/cordova-background-geolocation-SampleApp#66]
Hello,

I am facing some issues, which doesn't make sense for me. I have been trying to find out how to control when to locate, but without luck. I have tried to uncomment the line `bgGeo.start()` as it doesn't write to the console `BackgroundGeolocation ready`. I have the exact same code as the posted. Furthermore I have trying to let it check if the Location is enabled, but it doesn't react on an if statement. I have tested it by letting it write to the console log.

This is the code

`BackgroundGeo() {

    function onDeviceReady() {
        // Get a reference to the plugin.
        var bgGeo = ( < any > window).BackgroundGeolocation;

        //This callback will be executed every time a geolocation is recorded in the background.
        var callbackFn = function(location, taskId) {
            var coords = location.coords;
            var lat = coords.latitude;
            var lng = coords.longitude;
            console.log('- Location: ', JSON.stringify(location));

            // Must signal completion of your callbackFn.
            bgGeo.finish(taskId);
        };

        // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
        var failureFn = function(errorCode) {
            console.warn('- BackgroundGeoLocation error: ', errorCode);
        }

        // Listen to location events & errors.
        bgGeo.on('location', callbackFn, failureFn);
        // Fired whenever state changes from moving->stationary or vice-versa.
        bgGeo.on('motionchange', function(isMoving) {
            console.log('- onMotionChange: ', isMoving);
        });
        // Fired whenever a geofence transition occurs.
        bgGeo.on('geofence', function(geofence) {
            console.log('- onGeofence: ', geofence.identifier, geofence.location);
        });
        // Fired whenever an HTTP response is received from your server.
        bgGeo.on('http', function(response) {
            console.log('http success: ', response.responseText);
        }, function(response) {
            console.log('http failure: ', response.status);
        });

        // BackgroundGeoLocation is highly configurable.
        bgGeo.configure({
            // Geolocation config
            desiredAccuracy: 0,
            distanceFilter: 10,
            stationaryRadius: 25,
            // Activity Recognition config
            activityRecognitionInterval: 10000,
            stopTimeout: 5,
            // Application config
            debug: true, // <-- Debug sounds & notifications.
            stopOnTerminate: false,
            startOnBoot: true,
            // HTTP / SQLite config
            url: "http://your.server.com/locations",
            method: "POST",
            autoSync: true,
            maxDaysToPersist: 3,
            /*   headers: {  // <-- Optional HTTP headers
                   "X-FOO": "bar"
               },
               params: {   // <-- Optional HTTP params
                   "auth_token": "maybe_your_server_authenticates_via_token_YES?"
               }*/
        }, function(state) {
            // This callback is executed when the plugin is ready to use.
            console.log("BackgroundGeolocation ready: ", state);
            if (!state.enabled) {
                bgGeo.start();
            }
        });
    }
}`

**Comment by christocracy** [comment]
You have posted an issue about the SampleApp.  Are you having a problem with the SampleApp?

**Comment by Hudhud** [comment]
I have a problem with the code

**Comment by christocracy** [comment]
what sort of problem?

**Comment by Hudhud** [comment]
I can't control when to locate the user and for some reason I can't write to the console log under function  (state).

**Comment by christocracy** [comment]
>I can't control when to locate the user 

I don't understand what you're talking about.   All you have to do is toggle the top-right switch in the Demo app **on**.  then move.  The plugin knows when the device is moving and when it's stopped.  It automatically tracks the device when the device is determined to be moving.  For iOS, you need to travel about 200 meters before tracking begins.

Read the [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by Hudhud** [comment]
Sorry @christocracy, I created the issue on the wrong repository :( The other one is also yours: 
[https://github.com/transistorsoft/cordova-background-geolocation-lt](url)
Shall I create a new issue on the other repo?

**Comment by christocracy** [comment]
This repo is the demo app *for* Cordova-background-Geolocation plugin.

You should post issue here only for issues about the *demo code only*
