### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by carmenmitru** [transistorsoft/cordova-background-geolocation-SampleApp#67]
Hello,

After I type npm install I tried to run with ionic serve and I receive this error:
![image](https://cloud.githubusercontent.com/assets/6141479/24710781/1ce00ab4-19ec-11e7-82d7-c696b187f0a4.png)

How can I solve it?

**Comment by christocracy** [comment]
You cannot run the plugin in the browser.  The plugin implements native location and motion apis on an iOS or Android device.

It's like trying to use `cordova-plugin-camera` in a browser.  Your browser doesn't *have* a camera.

You must run it on a device or simulator.

**Comment by carmenmitru** [comment]
I tried to build the project as apk with ionic build android and it shows me an error
![image](https://cloud.githubusercontent.com/assets/6141479/24711184/3899c938-19ed-11e7-89dd-bf25bd5cfb51.png)

**Comment by christocracy** [comment]
In your Android SDK Manager, do you have the following 2 checked items installed?

![](https://www.dropbox.com/s/aiogjpjft3v6xfx/Screenshot%202017-04-05%2010.48.36.png?dl=1)

**Comment by carmenmitru** [comment]
yes are installed

**Comment by christocracy** [comment]
http://stackoverflow.com/questions/39621250/how-to-fix-com-android-builder-internal-aapt-aaptexception-failed-to-crunch-fil

**Comment by srikanth15794** [comment]
Is it possible to run using devapp in mobile , because im getting  timeout error while running ?

**Comment by christocracy** [comment]
@srikanth15974 I don’t know what you mean.  Do you adb logs?

**Comment by srikanth15794** [comment]
You said we can run the app only on mobile.. Iam asking about using Ionic dev app

**Comment by christocracy** [comment]
What is “Ionic dev app”?
