### ISSUE TITLE
License validation failure - I have a valid license

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-SampleApp#68]
Hello,

Having an issue with license validation... "License Validation Failure" for android.  It was working fine earlier, and I have a valid license. I'm not sure what happened.  Here is the relevant excerpt from my config.xml:

```xml
<widget id="com.company.app" version="0.0.5" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
...
    <preference name="cordova-background-geolocation-license" value="..." />
    <plugin name="cordova-background-geolocation">
        <variable name="LICENSE" value="..." />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Background location-tracking is required" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving" />
    </plugin>
...
</widget>
```

**Comment by christocracy** [comment]
This is not the place for license issues.  This is the Sample App.

Please search *existing* issues [at the repo](https://github.com/transistorsoft/cordova-background-geolocation/issues/1175)

**Comment by dtruel** [comment]
Hi I would, but my access to the repo exired.  I recently bought more licenses just a month or so ago, but for some reason I am still not able to access the repo.

**Comment by christocracy** [comment]
Email me your Order #.

http://www.transistorsoft.com/contact
