### ISSUE TITLE
License not valid on Android / Ionic 1

### ISSUE THREAD

**Issue by tinbsys** [transistorsoft/cordova-background-geolocation-SampleApp#69]
We use 
ionic 1: config.xml 
`  <plugin name="cordova-background-geolocation-lt" spec="^2.6.0">
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Uicación en segundo plano requerida"/>
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Ubicación en segundo plano requerida"/>
    <variable name="MOTION_USAGE_DESCRIPTION" value="Using the accelerometer increases battery-efficiency by intelligently toggling location-tracking only when the device is detected to be moving"/>
    <variable name="LICENSE" value="<key value received by email>"/>
  </plugin>
`
cordova-background-geolocation**-lt** (altought the code snippet sent to our email was <plugin name="cordova-background-geolocation"> )

> `c:\AppconMapa\AplicacionTransportista>cordova plugin list
cordova-background-geolocation-lt 2.6.0 "BackgroundGeolocation"`

When we deploy to an android device we get License validation failure message
![whatsapp image 2017-04-07 at 08 37 37](https://cloud.githubusercontent.com/assets/26820072/24820372/07f42e76-1bbf-11e7-8718-105f605c79b5.jpeg)

Thanks in advance, 
Javier

**Comment by christocracy** [comment]
Did you purchase a license?  The plugin will operate in "evaluation mode" if you didn't purchase a license.  It will only work in DEBUG builds.  You must [purchase a license](http://www.transistorsoft.com/shop/products/cordova-background-geolocation) to use in RELEASE builds.

[See here](https://github.com/transistorsoft/cordova-background-geolocation-lt#cordova-background-geolocation)

**Comment by tinbsys** [comment]
Yes, I have a premium license (customer info@tinbsys.com). Is there any other cause for this error? How can I troubleshoot this issue?

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-background-geolocation/issues/1175

**Comment by tinbsys** [comment]
Note: this happens when we do "ionic run android" with the device connected to the pc via USB

**Comment by christocracy** [comment]
This is not the place for License issues.
