### ISSUE TITLE
Android dependency issue

### ISSUE THREAD

**Issue by cjlucani** [transistorsoft/cordova-background-geolocation-SampleApp#7]
Hi,

Awesome plugin! Got it working beautifully with iOS, but having a tough time with Android...

Running 'cordova android build' throws this exception:

    A problem occurred configuring root project 'android'.
    > Could not resolve all dependencies for configuration ':_debugCompile'.
       > Could not find com.android.support:support-v4:22.2.0.
         Searched in the following locations:
             https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
             https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
             https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
             https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
             file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4-22.2.0.aar
             file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4.aar
             file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
             file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
         Required by:
             :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-base:7.8.0
       > Could not find com.android.support:mediarouter-v7:22.2.0.
         Searched in the following locations:
             https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
             https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
             https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
             https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
             file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7-22.2.0.aar
             file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7.aar
             file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
             file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
         Required by:
             :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-cast:7.8.0

Looks like I have the right dependencies in the sdk manager:

![screen shot 2015-09-11 at 12 46 42 pm](https://cloud.githubusercontent.com/assets/13773163/9806121/0e0a529a-5884-11e5-8e46-b61e25694893.png)
![screen shot 2015-09-11 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/13773163/9806120/0e09f9bc-5884-11e5-8218-d7605bcad5e2.png)

Path looks right...
   cordova-background-geolocation-SampleApp git:(master) echo $ANDROID_HOME
    /Users/[hidden]/.meteor/android_bundle/android-sdk

Any ideas?

Thanks!

**Comment by christocracy** [comment]
- See wiki:
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Help-it-Doesn't-Work
!!

- Open Android SDK manager.

- Ensure you have "Google Repository" installed.


On Thursday, September 10, 2015, cjlucani <notifications@github.com> wrote:

> Hi,
>
> Awesome plugin! Got it working beautifully with iOS, but having a tough
> time with Android...
>
> Running 'cordova android build' throws this exception:
>
> A problem occurred configuring root project 'android'.
> > Could not resolve all dependencies for configuration ':_debugCompile'.
>    > Could not find com.android.support:support-v4:22.2.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>          https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4.aar
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>      Required by:
>          :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-base:7.8.0
>    > Could not find com.android.support:mediarouter-v7:22.2.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>          https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7.aar
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>      Required by:
>          :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-cast:7.8.0
>
> Looks like I have the right dependencies in the sdk manager:
>
> [image: screen shot 2015-09-11 at 12 46 42 pm]
> <https://cloud.githubusercontent.com/assets/13773163/9806121/0e0a529a-5884-11e5-8e46-b61e25694893.png>
> [image: screen shot 2015-09-11 at 12 46 59 pm]
> <https://cloud.githubusercontent.com/assets/13773163/9806120/0e09f9bc-5884-11e5-8218-d7605bcad5e2.png>
>
> Path looks right...
> ➜ cordova-background-geolocation-SampleApp git:(master) echo $ANDROID_HOME
> /Users/[hidden]/.meteor/android_bundle/android-sdk
>
> Any ideas?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/7>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Oh, you have that installed.

However, you don't have "Android Support Repository" installed

On Thursday, September 10, 2015, cjlucani <notifications@github.com> wrote:

> Hi,
>
> Awesome plugin! Got it working beautifully with iOS, but having a tough
> time with Android...
>
> Running 'cordova android build' throws this exception:
>
> A problem occurred configuring root project 'android'.
> > Could not resolve all dependencies for configuration ':_debugCompile'.
>    > Could not find com.android.support:support-v4:22.2.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>          https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          https://jcenter.bintray.com/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/support-v4.aar
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
>      Required by:
>          :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-base:7.8.0
>    > Could not find com.android.support:mediarouter-v7:22.2.0.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          https://repo1.maven.org/maven2/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>          https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          https://jcenter.bintray.com/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7-22.2.0.aar
>          file:/Users/[hidden]/gdrive/web/code/repos/cordova-background-geolocation-SampleApp/platforms/android/src/android/libs/mediarouter-v7.aar
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.pom
>          file:/Users/[hidden]/.meteor/android_bundle/android-sdk/extras/google/m2repository/com/android/support/mediarouter-v7/22.2.0/mediarouter-v7-22.2.0.aar
>      Required by:
>          :android:unspecified > com.google.android.gms:play-services:7.8.0 > com.google.android.gms:play-services-cast:7.8.0
>
> Looks like I have the right dependencies in the sdk manager:
>
> [image: screen shot 2015-09-11 at 12 46 42 pm]
> <https://cloud.githubusercontent.com/assets/13773163/9806121/0e0a529a-5884-11e5-8e46-b61e25694893.png>
> [image: screen shot 2015-09-11 at 12 46 59 pm]
> <https://cloud.githubusercontent.com/assets/13773163/9806120/0e09f9bc-5884-11e5-8218-d7605bcad5e2.png>
>
> Path looks right...
> ➜ cordova-background-geolocation-SampleApp git:(master) echo $ANDROID_HOME
> /Users/[hidden]/.meteor/android_bundle/android-sdk
>
> Any ideas?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/issues/7>
> .
>


-- 
Snet form Gmail Mobile

**Comment by cjlucani** [comment]
Awesome! Thanks for the quick reply... installing now.

**Comment by cjlucani** [comment]
Installed. Works! Been looking at the screen too long - should have seen the missing dependency. Many thanks...
