### ISSUE TITLE
Location error 1

### ISSUE THREAD

**Issue by jessicastorm1986** [transistorsoft/cordova-background-geolocation-SampleApp#70]
It is giving me this message when I am clicking the bottom left black color arrow kind of icon. When I click the bottom right green icon, it changes to red and like it is finding  something continually.. Map shows I am in Adelaide though I am not

I am on oppo, please help.

**Comment by christocracy** [comment]
[Location Error Codes](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Location-Error-Codes)

"Permission Denied".  You didn't accept Location Permission or you have Location Services disabled.

**Comment by christocracy** [comment]
Also, at first boot, the plugin doesn't ask for permission until you toggle the switch on top-right.

![](https://camo.githubusercontent.com/abffbbf340639c1218f6b40c7e2b42993679cc24/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f6279616179657a70686b776e3336682f686f6d652d6672616d65642d3335302e706e673f646c3d31)
