### ISSUE TITLE
Server Address in HTTP&PERSISTENCE doesnt persist when app is closed

### ISSUE THREAD

**Issue by likeadoc** [transistorsoft/cordova-background-geolocation-SampleApp#71]
A custom server adress in the http&persistence submenu doesnt persist when the app gets closed both on android and iOS - it alway reverts back to http://192.168.11.100:8080/locations.

Cheers

**Comment by christocracy** [comment]
Yes, I fixed this.  Pull again on the repo.

**Comment by christocracy** [comment]
Oops, I think I forgot to push this bug fix

**Comment by likeadoc** [comment]
Haha:) got me there for a minute - i pulled it 1 hour ago
btw: short question offtopic - what does locationTimeout do? Unfortunately it isn´t document anywhere:)

**Comment by christocracy** [comment]
Ok, pull now.

`locationTimeout` isn't important.  It's the timeout before the plugin gives up fetching a location when a location is requested.  The default `60` is sufficient.

**Comment by likeadoc** [comment]
okok, thank you very much:)

**Comment by likeadoc** [comment]
hmmm now if i try to manually change the state from stational to moving i'm getting an alert "failed to changePace"

**Comment by likeadoc** [comment]
nevermind seems to be an error in cordova ... debug app works fine
