### ISSUE TITLE
please add more specific information on trackingmode=geofence

### ISSUE THREAD

**Issue by likeadoc** [transistorsoft/cordova-background-geolocation-SampleApp#72]
I couldn´t find any exact documentation on trackingmode=geofence.
My main questions are:
Does this work in background?
How accurate is it(in  background)?
How does it work?( are location updates triggered based on velocity or distance to the geofence?)
Cheers Alex

**Comment by christocracy** [comment]
Tracking mode is not a config option.

This the geofences only mode, engaged with #startGeofences.

This plugin has the word "background" in it for a very good reason.

**Comment by christocracy** [comment]
Geofences are triggered at the operating system level.  These are the native geofence apis being used.

Long press on map to add geofences.  Try them and see for yourself how accurate they are.

**Comment by likeadoc** [comment]
Thanks for the clarification:) I just was confused because everytime I activated the Background Tracking option in the sample app the trackingmode option changed from geofence to location - but that doesnt happen anymore.

**Comment by christocracy** [comment]
`trackingMode` is a read-only state property.  This state is toggled with the methods `#start` / `#startGeofences`.

**Comment by likeadoc** [comment]
Just for clarification - I was talking about the choosable option in the SampleApp that got reverted back from "geofence" to "location" everytime i activated the green switch in the main screen. 
![whatsapp image 2017-04-24 at 15 56 05](https://cloud.githubusercontent.com/assets/16107593/25340612/9bcdcb1c-2906-11e7-87db-a8d911231a11.jpeg)

**Comment by christocracy** [comment]
It's just a bug in the UI code.

**Comment by likeadoc** [comment]
Yeah I thought so too... Anyway thank you for your clarification!:)
