### ISSUE TITLE
The problem when scheduled location Tracking  in  ios

### ISSUE THREAD

**Issue by hatvott** [transistorsoft/cordova-background-geolocation-SampleApp#73]
Dear Chris,
we configured to automatically start and stop tracking with our calendar. But the application can't auto track the location on the next day.
We followed by your guide.
stopOnTerminate: false
startOnBoot: true;
Thank Chris so much!

**Comment by christocracy** [comment]
This is the sample app repo **of the plugin**.  It is not the place to post issues *about* the plugin.

Post issues at the repo.
