### ISSUE TITLE
Stop when close app

### ISSUE THREAD

**Issue by meggii** [transistorsoft/cordova-background-geolocation-SampleApp#74]
Background service send data when app is running and when app terminate background service stop sendindg data... how it works all time and how auto start every 2 min

**Comment by christocracy** [comment]
iOS or Android?

**Comment by christocracy** [comment]
See the docs for [stopOnTerminate](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#config-boolean-stoponterminate-true)

**Comment by meggii** [comment]
android
