### ISSUE TITLE
Build fails on parameters to addGeofences

### ISSUE THREAD

**Issue by pmalhotra1** [transistorsoft/cordova-background-geolocation-SampleApp#77]
configureBackgroundGeolocationForFirstTime() {

    console.log("Configuring for first time!");
    // 2. Listen to events
    this.backgroundGeolocation.on('location', this.onLocation.bind(this));
    this.backgroundGeolocation.on('heartbeat', this.onHeartBeat.bind(this));
    this.backgroundGeolocation.on('motionchange', this.onMotionChange.bind(this));
    this.backgroundGeolocation.on('geofence', this.onGeofence.bind(this));
    
    // 3. Configure it.
    this.backgroundGeolocation.configure(this.config, function(state)  {
      console.log('started ');
      this.backgroundGeolocation.addGeofences([
        notifyOnExit : true,
        notifyOnEntry : true,
        radius: 200,
        identifier: 'Location1',
        latitude: 38.9925839,
        longitude: -87.5652028]) ;

      if (!state.enabled) {
    this.backgroundGeolocation.startGeofences(function(state) {
      console.log('- Geofence-only monitoring started', state.trackingMode);
        });
      }
    });  
  }

--------- build error-----------
      L98:  identifier: 'Location1',
      L99:  latitude: 38.9925839,

[11:17:47]  typescript: src/providers/background-location.ts, line: 99
            ',' expected.

      L98:  identifier: 'Location1',
      L99:  latitude: 38.9925839,
     L100:  longitude: -87.5652028]) ;

[11:17:47]  typescript: src/providers/background-location.ts, line: 100
            ',' expected.

      L99:          latitude: 38.9925839,
     L100:          longitude: -87.5652028]) ;

[11:17:47]  typescript: src/providers/background-location.ts, line: 95
            Cannot find name 'notifyOnExit'.

      L94:  this.backgroundGeolocation.addGeofences([
      L95:    notifyOnExit : true,
      L96:    notifyOnEntry : true,
[11:17:47]  typescript: src/providers/background-location.ts, line: 96

            Cannot find name 'notifyOnEntry'.

[11:17:47]  typescript: src/providers/background-location.ts, line: 97
      L95:  notifyOnExit : true,
      L96:  notifyOnEntry : true,
      L97:  radius: 200,

            Cannot find name 'radius'.

      L96:  notifyOnEntry : true,
      L97:  radius: 200,
      L98:  identifier: 'Home',

[11:17:47]  typescript: src/providers/background-location.ts, line: 98
            Cannot find name 'identifier'.

      L97:  radius: 200,
      L98:  identifier: 'Location1',
[11:17:47]  typescript: src/providers/background-location.ts, line: 99
[11:17:47]  typescript: src/providers/background-location.ts, line: 100
      L99:  latitude: 33.9925839,

            Cannot find name 'latitude'.

      L98:  identifier: 'Location1',
      L99:  latitude: 38.9925839,
     L100:  longitude: -87.5652028]) ;

            Cannot find name 'longitude'.

      L99:          latitude: 38.9925839,
     L100:          longitude: -87.5652028]) ;

**Comment by pmalhotra1** [comment]
Was able to resolve the build.

**Comment by christocracy** [comment]
You didn't wrap your data in `{}`.
