### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PerryRylance** [transistorsoft/cordova-background-geolocation-SampleApp#82]
Windows
Phonegap
Samsung A5

Steps

- Unzip sample app into folder
- phonegap platform add android
- phonegap serve

On android screen

Application Error
net::ERR_FILE_NOT_FOUND (file:///data/user/0/com.adobe.phonegap.app/files/phonegapdevapp/www/index.html)

Even if I do add index.html, window.backgroundGeolocation is undefined

**Comment by christocracy** [comment]
You're new to this, aren't you?  

This is an Ionic 3 application.  There is **NO** `www/index.html`.
