### ISSUE TITLE
testing on ionic pro

### ISSUE THREAD

**Issue by blondie63** [transistorsoft/cordova-background-geolocation-SampleApp#87]
Try to packing with https://dashboard.ionicjs.com i've this error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Some idea?

**Comment by christocracy** [comment]
This has nothing to do with this repo.  This is between you and Ionic.
