### ISSUE TITLE
It makes runtime error when I add Http at the constructor of MainPage.

### ISSUE THREAD

**Issue by JoohyoungPark** [transistorsoft/cordova-background-geolocation-SampleApp#90]
I add a parameter of MainPage Constructor but it makes runtime error.
I tried to solve this error 7 hours but I can't.

```
core.es5.js:1084 ERROR Error: Uncaught (in promise): Error: No provider for ConnectionBackend!
```

I folk the project and works in it.
https://github.com/JoohyoungPark/cordova-background-geolocation-SampleApp/commit/01c34ddd90c953370095328154e2f02dbe18d084

I can not add any provider to a component.
It makes same runtime error.
Do I setup something?

**Comment by christocracy** [comment]
No idea.

**Comment by JoohyoungPark** [comment]
I fix it after upgrade all node packages.
