### ISSUE TITLE
property testservice never used, stalls build

### ISSUE THREAD

**Issue by Barryg86** [transistorsoft/cordova-background-geolocation-SampleApp#93]
Hi there, getting this error.  Anything I've done wrong / can I just remove form source?

[11:51:32]  tslint: ...c/cordova-background-geolocation-SampleApp-master/src/pages/advanced/advanced.ts, line: 110
            Property 'testService' is declared but never used.

     L109:      public settingsService: SettingsService,
     L110:      private testService: TestService) {

**Comment by christocracy** [comment]
It’s not an error.  Just a warning.

I imported my test service because I use it sometimes during development.

Ignore

**Comment by Barryg86** [comment]
All good - cheers
