### ISSUE TITLE
Is Cordova is only way to implement background tracking in iOS and Android.

### ISSUE THREAD

**Issue by kalyan711987kalyan** [transistorsoft/cordova-background-geolocation-SampleApp#94]
I looking to implement background tracking with native **iOS** and **Android** code. Is it possible with your SDK.
If yes, do you have any demo project.

**I don't want to use Cordova plugin because, I'm not familiar with Cordova**

**Comment by christocracy** [comment]
Yes.  This plugin has the word “background” in it for a reason.

This repo **IS** the demo project.
