### ISSUE TITLE
Can you please explain which plugin use for current location

### ISSUE THREAD

**Issue by musmanzpak** [transistorsoft/cordova-background-geolocation-SampleApp#95]
Hi, I like this Sample app very much. I need your help for getting user current location. This app is working well on my testing Android devices. Can you please explain which plugin you use in this app for getting the current location on google map? I will very thankful to you. 
I am founding help since last 15 days. :-(

**Comment by christocracy** [comment]
Sorry, I've been away on vacation.

Why don't you look at the [source](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/src/pages/hello-world/hello-world.ts#L101).  As you can see, that callback is executing the plugin's own [`#getCurrentPosition`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#getcurrentpositionsuccessfn-failurefn-options) method.
